import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,sendEmailVerification,signInWithEmailAndPassword,signOut,reload} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {getFirestore,collection,addDoc,doc,updateDoc,onSnapshot,serverTimestamp,query,orderBy,deleteField,deleteDoc,writeBatch} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
const app=initializeApp({apiKey:'AIzaSyCvfNXDQOYiiWr4XfoszYaCM8cV1tTUHxc',authDomain:'renew-outreach.firebaseapp.com',projectId:'renew-outreach',appId:'1:801810627803:web:53197465069a6724c1a0fe'});
const auth=getAuth(app),db=getFirestore(app),team=['paulospeople@gmail.com','renewhomeimprovement@proton.me'];
const counties=['Worcester','Franklin','Hampshire','Hampden','Middlesex','Norfolk','Tolland','Windham','Providence'];
const target='https://liveprojects.yourbusinessseen.com/renew/#home',root=document.getElementById('app');
let user=null,campaigns=[],leads=[],assets=[],events=[],active='',message='',error='',stops=[],pendingImport=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=()=>`${error?`<p role="alert" class="message error">${esc(error)}</p>`:''}${message?`<p role="status" class="message">${esc(message)}</p>`:''}`;
async function run(fn){error='';message='';try{await fn()}catch(e){error=e.message||'Action failed';console.error(e)}render()}
function cleanup(){stops.forEach(f=>f());stops=[];campaigns=[];leads=[];assets=[];events=[]}
function listen(){cleanup();for(const [name,coll] of [['campaigns','campaigns'],['leads','leads'],['assets','campaignAssets'],['events','campaignEvents']]){
 stops.push(onSnapshot(query(collection(db,coll),orderBy(name==='campaigns'||name==='leads'?'updatedAt':'createdAt','desc')),s=>{const items=s.docs.map(d=>({id:d.id,...d.data()}));if(name==='campaigns')campaigns=items;if(name==='leads')leads=items;if(name==='assets')assets=items;if(name==='events')events=items;render()},e=>{error=`${name}: ${e.message}`;render()}))}}
onAuthStateChanged(auth,u=>{user=u;if(u?.emailVerified&&team.includes(u.email))listen();else cleanup();render()});
function parseDelimited(text,delimiter){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){field+='"';i++}else if(ch==='"')quoted=false;else field+=ch}else if(ch==='"')quoted=true;else if(ch===delimiter){row.push(field);field=''}else if(ch==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=ch}if(quoted)throw Error('The list has an unmatched quote.');if(field||row.length){row.push(field.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(v=>v.trim()))}
function normalizeCounty(value){return counties.find(c=>c.toLowerCase()===String(value||'').trim().toLowerCase())||''}
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
function prepareList(text,fileName,fallbackCounty,source){if(!active)throw Error('Save or select a campaign first.');if(!source.trim())throw Error('Enter the real source of this list.');if(text.length>1200000)throw Error('List too large; import up to 500 records at a time.');
 const ext=fileName.split('.').pop().toLowerCase(),delim=ext==='tsv'?'\t':ext==='csv'?',':null;let rows=[],skipped=0;
 if(delim){const grid=parseDelimited(text.replace(/^\uFEFF/,''),delim);if(!grid.length)throw Error('The list is empty.');const headers=grid[0].map(x=>x.trim().toLowerCase().replace(/[ _-]/g,''));const idx=(...aliases)=>headers.findIndex(h=>aliases.includes(h));const ei=idx('email','emailaddress','mail'),ni=idx('name','fullname'),ci=idx('county'),si=idx('source'),pi=idx('permission','consent'),oi=idx('notes');if(ei<0)throw Error('The first row needs an email column.');rows=grid.slice(1).map(r=>({email:r[ei],name:r[ni]||'',county:r[ci]||fallbackCounty,source:r[si]||source,permission:r[pi]||'unknown',notes:r[oi]||''}))}
 else rows=text.split(/\r?\n/).map(line=>({email:line.trim(),name:'',county:fallbackCounty,source,permission:'unknown',notes:''})).filter(x=>x.email);
 if(rows.length>500)throw Error('Import up to 500 addresses at a time.');const seen=new Set(leads.map(l=>l.email.toLowerCase())),ready=[];
 for(const raw of rows){const email=String(raw.email||'').trim().toLowerCase(),county=normalizeCounty(raw.county),permission=String(raw.permission||'unknown').trim().toLowerCase();if(!validEmail(email)||!county||!['unknown','opted-in','suppressed'].includes(permission)||!String(raw.source||'').trim()||seen.has(email)){skipped++;continue}seen.add(email);ready.push({email,name:String(raw.name||'').trim().slice(0,200),county,source:String(raw.source).trim().slice(0,500),permission,notes:String(raw.notes||'').trim().slice(0,2000),campaignId:active,stage:'new'})}
 return {rows:ready,skipped,total:rows.length,fileName};}
async function importList(){if(!pendingImport||!active)throw Error('Preview a list first.');if(!pendingImport.rows.length)throw Error('No valid new records to import.');const imported=pendingImport.rows.length;for(let i=0;i<imported;i+=200){const batch=writeBatch(db);for(const row of pendingImport.rows.slice(i,i+200))batch.set(doc(collection(db,'leads')),{...row,updatedAt:serverTimestamp()});await batch.commit()}await addDoc(collection(db,'campaignEvents'),{campaignId:active,type:'note',note:`Imported ${imported} contacts from ${pendingImport.fileName}. ${pendingImport.skipped} rows skipped.`,actor:user.email,createdAt:serverTimestamp()});pendingImport=null;message=`Imported ${imported} real contacts.`}
async function uploadImage(file){if(!active)throw Error('Save or select a campaign first.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Use a PNG, JPEG, or WebP image.');if(file.size>180000)throw Error('Image must be under 180 KB on this plan.');if(assets.filter(a=>a.campaignId===active).length>=4)throw Error('Maximum four images per campaign.');const dataUrl=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(Error('Could not read image'));fr.readAsDataURL(file)});if(dataUrl.length>250000)throw Error('Image is too large after encoding.');const batch=writeBatch(db);batch.set(doc(collection(db,'campaignAssets')),{campaignId:active,fileName:file.name.slice(0,200),mime:file.type,dataUrl,addedBy:user.email,createdAt:serverTimestamp()});const selected=campaigns.find(c=>c.id===active);if(selected?.status==='approved')batch.update(doc(db,'campaigns',active),{status:'draft',approvedBy:deleteField(),approvedAt:deleteField(),lastEditedBy:user.email,updatedAt:serverTimestamp()});await batch.commit();message='Image added to the campaign preview. Any approval was reset.'}
async function removeImage(id){const selected=campaigns.find(c=>c.id===active),batch=writeBatch(db);batch.delete(doc(db,'campaignAssets',id));if(selected?.status==='approved')batch.update(doc(db,'campaigns',active),{status:'draft',approvedBy:deleteField(),approvedAt:deleteField(),lastEditedBy:user.email,updatedAt:serverTimestamp()});await batch.commit();message='Image removed. Any approval was reset.'}
function render(){if(!user){root.innerHTML=`<main class="login"><h1>Renew Outreach</h1><p>Private workspace for Wesley and Mark</p>${status()}<form id="login"><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required minlength="6" autocomplete="current-password"></label><div class="actions"><button type="submit">Sign in</button><button class="secondary" type="button" id="register">Create team account</button></div></form></main>`;document.getElementById('login').onsubmit=e=>{e.preventDefault();run(()=>signInWithEmailAndPassword(auth,e.target.email.value.trim().toLowerCase(),e.target.password.value))};document.getElementById('register').onclick=()=>run(async()=>{let f=document.getElementById('login'),email=f.email.value.trim().toLowerCase();if(!team.includes(email))throw Error('Use an approved team email.');if(!f.password.value)throw Error('Enter a password.');const result=await createUserWithEmailAndPassword(auth,email,f.password.value);await sendEmailVerification(result.user);message='Check your inbox to verify your email, then refresh verification.'});return}
if(!user.emailVerified||!team.includes(user.email)){root.innerHTML=`<main><h1>${team.includes(user.email)?'Verify your email to continue':'Access restricted'}</h1><p>${team.includes(user.email)?`We created the account for ${esc(user.email)}. Open the Firebase verification email, click its link, then select Refresh verification here. Check spam if you do not see the email.`:'Only the two approved team addresses can access records.'}</p>${status()}<div class="actions">${team.includes(user.email)?'<button id="refresh">Refresh verification</button><button id="resend" class="secondary">Resend verification</button>':''}<button id="logout" class="secondary">Sign out</button></div></main>`;document.getElementById('logout').onclick=()=>signOut(auth);if(team.includes(user.email)){document.getElementById('refresh').onclick=()=>run(async()=>{await reload(user);if(user.emailVerified)listen();else message='Still waiting for verification.'});document.getElementById('resend').onclick=()=>run(async()=>{await sendEmailVerification(user);message='Verification email sent.'})}return}
const mark=user.email===team[1],selected=campaigns.find(c=>c.id===active),myLeads=leads.filter(l=>l.campaignId===active),myAssets=assets.filter(a=>a.campaignId===active),myEvents=events.filter(e=>e.campaignId===active);const metric=(stage)=>myLeads.filter(l=>stage==='contacted'?['contacted','responded','walkthrough-booked'].includes(l.stage):stage==='responded'?['responded','walkthrough-booked'].includes(l.stage):l.stage===stage).length;
root.innerHTML=`<header><div><strong>RENEW</strong><span>Outreach workspace</span></div><div>${esc(user.email)}<button id="logout" class="secondary">Sign out</button></div></header><main><section class="hero"><p>WORCESTER + ADJACENT COUNTIES</p><h1>Make every outreach step clear.</h1><p>Prepare real campaigns, import traceable contacts, and direct interest to Renew’s walkthrough app.</p><a href="${target}" target="_blank" rel="noreferrer">Open customer app ↗</a></section>${status()}<div class="message">${active?`Campaign selected: <strong>${esc(selected?.subject||'Draft')}</strong>. <a href="#images">Upload pictures ↓</a> · <a href="#lists">Upload CSV or contact list ↓</a>`:'To upload pictures or a CSV list, first select a saved campaign below. If you have none, enter a subject and email message, then select <strong>Save draft</strong>. The upload sections will appear.'}</div><div class="grid"><section class="card"><h2>Campaign desk</h2><p>Draft → Mark approval. Email sending is still unavailable until the Postmark backend is configured.</p><button id="new" class="secondary">New draft</button><div class="list">${campaigns.map(c=>`<button type="button" data-campaign="${esc(c.id)}" class="${active===c.id?'selected':''}">${esc(c.subject)}<small>${esc(c.status)}</small></button>`).join('')}</div><label>Subject<input id="subject" maxlength="180" value="${esc(selected?.subject||'')}"></label><label>Email message<textarea id="body" rows="9" maxlength="10000">${esc(selected?.body||'')}</textarea></label><p class="hint">Images appear in the campaign preview and are stored for the eventual email send integration.</p><div class="actions"><button id="save">Save draft</button>${mark&&selected?.status!=='approved'?'<button id="approve" class="secondary">Approve saved draft</button>':''}</div>${selected?`<p>Status: <strong>${esc(selected.status)}</strong>${selected.approvedBy?` · Approved by ${esc(selected.approvedBy)}`:''}</p>`:''}
${active?`<hr><h3 id="images">Upload pictures (${myAssets.length}/4)</h3><p class="hint">PNG, JPEG or WebP, at most 180 KB each. Stored privately with this campaign. Email delivery remains disabled.</p><label>Choose a picture<input type="file" id="image" accept="image/png,image/jpeg,image/webp"></label><div class="images">${myAssets.map(a=>`<figure><img src="${a.dataUrl}" alt="${esc(a.fileName)}"><figcaption>${esc(a.fileName)} <button type="button" class="secondary" data-remove="${esc(a.id)}">Remove</button></figcaption></figure>`).join('')}</div><h3>Message preview</h3><div class="preview"><strong>${esc(selected?.subject||'')}</strong><p>${esc(selected?.body||'').replace(/\n/g,'<br>')}</p>${myAssets.map(a=>`<img src="${a.dataUrl}" alt="${esc(a.fileName)}">`).join('')}<p><a href="${target}" target="_blank" rel="noreferrer">Request a walkthrough</a></p></div>`:''}</section>
<section class="card"><h2>Lead records</h2><p>Add only real prospects. Record their source and permission status.</p><form id="lead"><label>Email<input name="email" type="email" required></label><label>Name<input name="name"></label><label>County<select name="county">${counties.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Source<input name="source" required placeholder="Where did this contact come from?"></label><label>Permission<select name="permission"><option value="unknown">Unknown</option><option value="opted-in">Opted in</option><option value="suppressed">Do not contact</option></select></label><label>Notes<textarea name="notes"></textarea></label><button type="submit">Save lead</button></form><h3>Saved leads (${leads.length})</h3><div class="list">${leads.map(l=>`<div class="lead"><strong>${esc(l.name||l.email)}</strong><small>${esc(l.email)} · ${esc(l.county)} · ${esc(l.permission)}</small><small>Source: ${esc(l.source)}</small>${active&&l.campaignId===active?`<label>Progress<select data-stage="${esc(l.id)}">${[['new','New'],['contacted','Contacted'],['responded','Responded'],['walkthrough-booked','Walkthrough booked']].map(([v,n])=>`<option value="${v}" ${l.stage===v?'selected':''}>${n}</option>`).join('')}</select></label>`:''}</div>`).join('')}</div></section></div>
${active?`<div class="grid lower"><section class="card"><h2 id="lists">Upload CSV or contact list</h2><p>CSV, TSV, or TXT (one email per line). CSV/TSV must have an <code>email</code> header; optional columns: name, county, source, permission, notes. Maximum 500 rows per import. No sending happens on import.</p><label>Real source of this list<input id="list-source" placeholder="Example: signups from your website"></label><label>County, if the whole list belongs to one county<select id="list-county"><option value="">Use county in file / unknown</option>${counties.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Choose file<input type="file" id="list-file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values,text/plain"></label><button id="preview-list" class="secondary">Preview list</button>${pendingImport?`<div class="message"><strong>${pendingImport.rows.length} ready</strong> · ${pendingImport.skipped} skipped (duplicate, invalid email, missing county/source, or invalid permission).<br>${pendingImport.rows.slice(0,4).map(r=>esc(r.email)+' · '+esc(r.county)).join('<br>')}</div><button id="import-list" ${pendingImport.rows.length?'':'disabled'}>Import ${pendingImport.rows.length} contacts</button>`:''}</section><section class="card"><h2>Campaign progress</h2><p>Team updates only. Opens, clicks, and email delivery are not tracked yet.</p><div class="metrics"><div><strong>${myLeads.length}</strong><small>Contacts</small></div><div><strong>${metric('contacted')}</strong><small>Contacted</small></div><div><strong>${metric('responded')}</strong><small>Responded</small></div><div><strong>${metric('walkthrough-booked')}</strong><small>Walkthroughs</small></div></div><label>Record activity<select id="event-type"><option value="note">Note</option><option value="contacted">Contacted</option><option value="response">Response</option><option value="walkthrough">Walkthrough</option></select></label><label>What happened?<textarea id="event-note" maxlength="2000" rows="3"></textarea></label><button id="log-event">Add to history</button><h3>History</h3><div class="list">${myEvents.map(e=>`<div class="lead"><strong>${esc(e.type)}</strong><small>${esc(e.note)}</small><small>${esc(e.actor)} · ${e.createdAt?.toDate?.().toLocaleString()||'Just now'}</small></div>`).join('')||'<p>No activity recorded yet.</p>'}</div></section></div>`:''}</main>`;
document.getElementById('logout').onclick=()=>signOut(auth);document.getElementById('new').onclick=()=>{active='';pendingImport=null;render()};document.querySelectorAll('[data-campaign]').forEach(b=>b.onclick=()=>{active=b.dataset.campaign;pendingImport=null;render()});
document.getElementById('save').onclick=()=>run(async()=>{const subject=document.getElementById('subject').value.trim(),body=document.getElementById('body').value.trim();if(!subject||!body)throw Error('Add a subject and message.');const data={subject,body,status:'draft',lastEditedBy:user.email,updatedAt:serverTimestamp()};if(active)await updateDoc(doc(db,'campaigns',active),{...data,approvedBy:deleteField(),approvedAt:deleteField()});else active=(await addDoc(collection(db,'campaigns'),data)).id;message='Draft saved. Edits reset approval.'});
if(mark&&selected?.status!=='approved')document.getElementById('approve').onclick=()=>run(async()=>{if(document.getElementById('subject').value!==selected.subject||document.getElementById('body').value!==selected.body)throw Error('Save edits before approval.');await updateDoc(doc(db,'campaigns',active),{status:'approved',approvedBy:user.email,approvedAt:serverTimestamp(),lastEditedBy:user.email,updatedAt:serverTimestamp()});message='Campaign approved.'});
document.getElementById('lead').onsubmit=e=>{e.preventDefault();run(async()=>{const f=e.target,email=f.email.value.trim().toLowerCase(),source=f.source.value.trim();if(!source)throw Error('Record the real source.');if(leads.some(l=>l.email.toLowerCase()===email))throw Error('This email is already recorded.');await addDoc(collection(db,'leads'),{email,name:f.name.value.trim(),county:f.county.value,source,permission:f.permission.value,notes:f.notes.value.trim(),campaignId:active||'',stage:'new',updatedAt:serverTimestamp()});message='Lead saved. No message was sent.'})};
if(active){document.getElementById('image').onchange=e=>{const file=e.target.files[0];if(file)run(()=>uploadImage(file))};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Remove this image from the campaign?'))run(()=>removeImage(b.dataset.remove))});
document.getElementById('preview-list').onclick=()=>run(async()=>{const file=document.getElementById('list-file').files[0];if(!file)throw Error('Choose a CSV, TSV, or TXT file.');if(!/\.(csv|tsv|txt)$/i.test(file.name))throw Error('Choose a CSV, TSV, or TXT file.');pendingImport=prepareList(await file.text(),file.name,document.getElementById('list-county').value,document.getElementById('list-source').value);message=`Preview ready: ${pendingImport.rows.length} contacts, ${pendingImport.skipped} skipped.`});
if(pendingImport)document.getElementById('import-list').onclick=()=>run(importList);
document.getElementById('log-event').onclick=()=>run(async()=>{const note=document.getElementById('event-note').value.trim();if(!note)throw Error('Describe what happened.');await addDoc(collection(db,'campaignEvents'),{campaignId:active,type:document.getElementById('event-type').value,note,actor:user.email,createdAt:serverTimestamp()});message='Activity recorded.'});
document.querySelectorAll('[data-stage]').forEach(sel=>sel.onchange=()=>run(async()=>{const lead=leads.find(l=>l.id===sel.dataset.stage),stage=sel.value;if(!lead||lead.stage===stage)return;const batch=writeBatch(db);batch.update(doc(db,'leads',lead.id),{stage,updatedAt:serverTimestamp()});batch.set(doc(collection(db,'campaignEvents')),{campaignId:active,type:stage==='contacted'?'contacted':stage==='responded'?'response':stage==='walkthrough-booked'?'walkthrough':'note',note:`Updated ${lead.email} to ${stage}.`,actor:user.email,createdAt:serverTimestamp()});await batch.commit();message='Progress updated.'}))}
}
